DATABASE:
  HOST: "localhost"
  PORT: "3306"
  DATABASE: "EasterEggHunt"
  USERNAME: "root"
  PASSWORD: "root"
REGION:
  UPPERREGION:
    X: -54
    Y: 88
    Z: 48
  LOWERREGION:
    X: -33
    Y: 63
    Z: 4
EGG:
  EGGTOTAL:
  EGGBLOCK: PLAYER_HEAD
  # The radius of the map in order to count all of the eggs.
LANG:
  DATABASE:
    CONNECTIONERROR: "&cA database error has occurred, please contact an Administrator."
    CONNECTIONSUCCESS: "&aDatabase connected successfully."
  COMMAND:
    NOTAPLAYER: "&cYou must be a player to run this command."
    INSUFFICENTPERMISSIONS: "&cYou do not have permission to use this command."
    COMMANDINCOMPLETE: "&cThis command is incomplete, please refer to the command guide for reference."
  EGG:
    EGGFOUND: "&aYou have found an egg."
    EGGALREADYFOUND: "&eYou have already found this egg."
    EGGCOUNT: "&eYou have found &l&6%FOUNDEGGS%/%NUMBEROFEGGS% &r&eeggs."
    # Use %PLAYER% to display players name, use %NUMBEROFEGGS% to display number of eggs.
    EGGCOLLECTIONMILESTONEREACHED: "&e&l%PLAYER% &5has collected &e&l%NUMBEROFEGGS% &r&5eggs!"