DATABASE:
  HOST: "localhost"
  PORT: "3306"
  DATABASE: "EasterEggHunt"
  USERNAME: "root"
  PASSWORD: "root"
SOUND:
  EGGCOLLECTION: ""
  EGGALREADYCOLLECTED: ""
  EGGCOLLECTIONMILESTONE: ""
LANG:
  DATABASE:
    CONNECTIONERROR: "&cA database error has occurred, please contact an Administrator."
    CONNECTIONSUCCESS: "&aDatabase connected successfully."