DATABASE:
  HOST: "localhost"
  PORT: "3306"
  DATABASE: "EasterEggHunt"
  USERNAME: "root"
  PASSWORD: "root"
EGG:
  # Respawn Timer is in Ticks [default is 1200, 1 minute]
  RESPAWNTIMER: 1200
SOUND:
  EGGFOUND: "ENTITY_WITHER_BREAK_BLOCK"
  EGGALREADYFOUND: "BLOCK_NOTE_BLOCK_SNARE"
  MINORMILESTONE: "UI_TOAST_CHALLENGE_COMPLETE"
  MAJORMILESTONE: "ENTITY_ENDER_DRAGON_DEATH"
LANG:
  DATABASE:
    CONNECTIONERROR: "&cA database error has occurred, please contact an Administrator."
    CONNECTIONSUCCESS: "&aDatabase connected successfully."
  COMMAND:
    NOTAPLAYER: "&cYou must be a player to run this command."
    INSUFFICENTPERMISSIONS: "&cYou do not have permission to use this command."
    COMMANDINCOMPLETE: "&cThis command is incomplete, please refer to the command guide for reference."
  EGG:
    EGGFOUND: "&aYou have found an egg."
    EGGALREADYFOUND: "&eYou have already found this egg."
    EGGCOUNT: "&eYou have found &l&6%NUMBEROFEGGS% &r&eeggs."
    # Use %PLAYER% to display players name, use %NUMBEROFEGGS% to display number of eggs.
    EGGCOLLECTIONMILESTONEREACHED: "&e&l%PLAYER% &5has collected &e&l%NUMBEROFEGGS% &r&5eggs!"