DATABASE:
  HOST: "localhost"
  PORT: "3306"
  DATABASE: "EasterEggHunt"
  USERNAME: "root"
  PASSWORD: "root"
LANG:
  DATABASE:
    CONNECTIONERROR: "&cA database error has occurred, please contact an Administrator."
    CONNECTIONSUCCESS: "&aDatabase connected successfully."
  EGG:
    EGGFOUND: "&aYou have found an egg"
    EGGALREADYFOUND: "&eYou have already found this egg."
    # Use %PLAYER% to display players name, use %NUMBEROFEGGS% to display number of eggs.
    EGGCOLLECTIONMILESTONEREACHED: "&5%PLAYER% has collected %NUMBEROFEGGS% eggs!"