database:
  host: "localhost"
  port: "3306"
  database: "EasterEggHunt"
  username: "root"
  password: "password"
lang:
  databaseerror: "&cA database error has occurred, please contact an Administrator."