main: org.modularsoft.PlayerHeadHunt.PlayerHeadHuntMain
name: PlayerHeadHunt
description: An Player Head Hunt minigame.
version: 1.2.0
author: ModularSoft
api-version: 1.19
depend: [WorldEdit]

commands:
  heads:
    description: Grab the amount of heads you have.
    usage: /heads
    aliases: [eggs, presents]
  clearheads:
    description: Clear all heads from yourself.
    usage: /clearheads
    aliases: [cleareggs, clearpresents]
  countheads:
    description: Recalculates the number of heads in the world.
    usage: /countheads
    aliases: [counteggs, countpresents]
  leaderboard:
    description: Show the 5 best heads hunters on the Server.
    usage: /leaderboard
    aliases: [lb]