main: com.modularenigma.EasterEggHunt.EasterEggHuntMain
name: EasterEggHunt
description: An Easter Egg Hunt minigame for the Easter break for Crafting For Christ.
version: ${project.version}
author: ModularEnigma
api-version: 1.18
depend: [WorldEdit]

commands:
  eggs:
    description: Grab the amount of eggs you have.
    usage: /eggs
  cleareggs:
    description: Clear all eggs from yourself.
    usage: /cleareggs
  counteggs:
    description: Recalculates the number of eggs in the world.
    usage: /counteggs
  leaderboardeggs:
    description: Show the 10 best egg hunters in the world.
    usage: /leaderboardeggs
    aliases: [lb, leaderboard]